Class ImageSearchVideo.Production Extends Ens.Production
{

XData ProductionDefinition
{
<Production Name="ImageSearchVideo.Production" LogGeneralTraceEvents="false">
  <Description></Description>
  <ActorPoolSize>2</ActorPoolSize>
  <Item Name="ImageSearchVideo.BO" Category="" ClassName="ImageSearchVideo.BO" PoolSize="1" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>
  <Item Name="ImageSearchVideo.BussinessProcess" Category="" ClassName="ImageSearchVideo.BussinessProcess" PoolSize="1" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>
  <Item Name="ImageSearchVideo.BS" Category="" ClassName="ImageSearchVideo.BS" PoolSize="0" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>
</Production>
}

}

